### ISSUE TITLE
bug: do not work on windows 

### ISSUE THREAD

**Issue by nanakura** [mumu-lhl/eaf-pyqterminal#33]
It doesn't run properly on Windows.
Here are some error logs:

```python
Traceback (most recent call last):
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\site-lisp\emacs-application-framework\core\utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\site-lisp\emacs-application-framework\eaf.py", line 156, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\site-lisp\emacs-application-framework\eaf.py", line 171, in create_buffer
    spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "c:/Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal/eaf_pyqterm_buffer.py", line 13, in <module>
    from eaf_pyqterm_frontend import FrontendWidget
  File "c:\Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal\eaf_pyqterm_frontend.py", line 26, in <module>
    import eaf_pyqterm_backend as backend
  File "c:\Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal\eaf_pyqterm_backend.py", line 13, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

When I changed "platform" to "platform.system()", the error log became:

```
Traceback (most recent call last):
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\site-lisp\emacs-application-framework\core\utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\site-lisp\emacs-application-framework\eaf.py", line 156, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Islatan\AppData\Roaming\.emacs.d\site-lisp\emacs-application-framework\eaf.py", line 174, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "c:/Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal/eaf_pyqterm_buffer.py", line 23, in __init__
    term = FrontendWidget(argv, start_directory)
  File "c:\Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal\eaf_pyqterm_frontend.py", line 108, in __init__
    self.backend = backend.Backend(self.columns, self.rows, argv, start_directory)
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal\eaf_pyqterm_backend.py", line 104, in __init__
    self.pty = Pty(width, height, argv, start_directory)
               ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal\eaf_pyqterm_backend.py", line 35, in __init__
    self._spawn_winpty(env, argv, start_directory)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal\eaf_pyqterm_backend.py", line 50, in _spawn_winpty
    self.pty = pty.spawn(
               ~~~~~~~~~^
        list(argv[0]) + argv,
        ^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        (env["COLUMNS"], env["LINES"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Islatan\AppData\Roaming\Python\Python313\site-packages\winpty\ptyprocess.py", line 82, in spawn
    raise FileNotFoundError(
    ...<2 lines>...
    )
FileNotFoundError: The command was not found or was not executable: p.
```

**Comment by mumu-lhl** [comment]
Can you check the results of running eaf--generate-terminal-command?

**Comment by nanakura** [comment]
> Can you check the results of running eaf--generate-terminal-command?

how to running eaf--generate-terminal-command

**Comment by nanakura** [comment]
> Can you check the results of running eaf--generate-terminal-command?

When I modified _spawn_winpty
```py
    def _spawn_winpty(self, env, argv, start_directory):
        self.pty = pty.spawn(
            "powershell.exe",
            start_directory,
            env,
            (int(env["COLUMNS"]), int(env["LINES"])),
        )
```
new error occur:
```py
Exception in thread Thread-4 (read):
Traceback (most recent call last):
  File "e:\Python\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "e:\Python\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal\eaf_pyqterm_backend.py", line 152, in read
    self.write_to_screen(data)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "c:\Users/Islatan/AppData/Roaming/.emacs.d/site-lisp/emacs-application-framework/app/pyqterminal\eaf_pyqterm_backend.py", line 120, in write_to_screen
    into = data.split(b"\x1b[?1049h")
TypeError: must be str or None, not bytes
```
it seems that the type of data is str

**Comment by mumu-lhl** [comment]
Try the latest commit
